name: health_and_doctor_appointment
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  awesome_notifications: ^0.9.3+1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.9
  cool_alert: ^2.0.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_spinkit: ^5.2.0
  flutter_tabler_icons: ^1.25.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  icons_plus: ^5.0.0
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  provider: ^6.1.2
  quick_actions: ^1.0.7
  typicons_flutter: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
