// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdApk025iiG_f6BmCd17221Lji8idjRbw',
    appId: '1:69949513569:web:abb382dc7fa84564bf2f20',
    messagingSenderId: '69949513569',
    projectId: 'appointment-app-b1474',
    authDomain: 'appointment-app-b1474.firebaseapp.com',
    storageBucket: 'appointment-app-b1474.appspot.com',
    measurementId: 'G-NK6FL5WGF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs9ii6kZwRr9906vzhQ7TpZFPbX9QsHh8',
    appId: '1:69949513569:android:86f3bf1d076b3a08bf2f20',
    messagingSenderId: '69949513569',
    projectId: 'appointment-app-b1474',
    storageBucket: 'appointment-app-b1474.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF3FM0VXe0h8AzHQGP69hZR5VunE0Gink',
    appId: '1:69949513569:ios:2bcfb2206dd8d734bf2f20',
    messagingSenderId: '69949513569',
    projectId: 'appointment-app-b1474',
    storageBucket: 'appointment-app-b1474.appspot.com',
    iosBundleId: 'com.example.healthAndDoctorAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF3FM0VXe0h8AzHQGP69hZR5VunE0Gink',
    appId: '1:69949513569:ios:9ad1212215e4ce18bf2f20',
    messagingSenderId: '69949513569',
    projectId: 'appointment-app-b1474',
    storageBucket: 'appointment-app-b1474.appspot.com',
    iosBundleId: 'com.example.healthAndDoctorAppointment.RunnerTests',
  );
}
